#!/bin/bash
# SEO Configuration Setup Guide
# Follow these steps to complete your SEO setup

echo "====================================="
echo "explorethebuzz SEO Configuration Guide"
echo "====================================="
echo ""

# Step 1: AdSense Configuration
echo "📍 STEP 1: Google AdSense Setup"
echo "=================================="
echo "1. Go to https://adsense.google.com"
echo "2. Sign in with your Google account"
echo "3. Click 'Get Started' and follow the setup wizard"
echo "4. Once approved, go to Settings → Account → Publisher ID"
echo "5. Copy your Publisher ID (ca-pub-xxxxxxxxxxxxxxxx)"
echo ""
echo "Then update:"
echo "  File: src/app/layout.js"
echo "  Line: ~21 (search for YOUR_ADSENSE_ID)"
echo "  Replace: ca-pub-YOUR_ADSENSE_ID with your actual ID"
echo ""

# Step 2: Google Analytics Configuration
echo "📍 STEP 2: Google Analytics Setup"
echo "===================================="
echo "1. Go to https://analytics.google.com"
echo "2. Click 'Start Measuring'"
echo "3. Create a new property for your website"
echo "4. Select 'Web' as the platform"
echo "5. Enter your website details"
echo "6. Get your Measurement ID (format: G-XXXXXXXXXX)"
echo ""
echo "Then update:"
echo "  File: src/app/layout.js"
echo "  Line: ~24 (search for YOUR_GOOGLE_ANALYTICS_ID)"
echo "  Replace: G-YOUR_GOOGLE_ANALYTICS_ID with your Measurement ID"
echo ""

# Step 3: Google Search Console Setup
echo "📍 STEP 3: Google Search Console Setup"
echo "========================================"
echo "1. Go to https://search.google.com/search-console"
echo "2. Click 'Add Property'"
echo "3. Enter your website URL"
echo "4. Verify ownership (choose any method):"
echo "   - HTML file method"
echo "   - HTML tag method (easiest - copy from verification details)"
echo "   - Google Analytics method"
echo "   - Google Tag Manager method"
echo "5. Copy the verification code/meta tag"
echo ""
echo "Then update:"
echo "  File: src/app/layout.js"
echo "  Line: ~22 (search for google-site-verification)"
echo "  Replace: YOUR_GOOGLE_SITE_VERIFICATION_CODE with the verification code"
echo ""

# Step 4: Submit Sitemaps
echo "📍 STEP 4: Submit Sitemap to Search Engines"
echo "============================================="
echo "Google Search Console:"
echo "  1. Go to your Google Search Console property"
echo "  2. Left menu → Sitemaps"
echo "  3. Enter: https://yourwebsite.com/sitemap.xml"
echo "  4. Click Submit"
echo ""
echo "Bing Webmaster Tools:"
echo "  1. Go to https://www.bing.com/webmasters"
echo "  2. Add your site"
echo "  3. Go to Sitemaps"
echo "  4. Enter: https://yourwebsite.com/sitemap.xml"
echo "  5. Submit"
echo ""

# Step 5: Deploy and Verify
echo "📍 STEP 5: Deploy and Verification"
echo "===================================="
echo "1. Build your project:"
echo "   npm run build"
echo ""
echo "2. Deploy to production (Vercel, Netlify, etc.)"
echo ""
echo "3. Verify deployment:"
echo "   - Check that https://yourwebsite.com/sitemap.xml is accessible"
echo "   - Check that https://yourwebsite.com/robots.txt is accessible"
echo "   - Check that https://yourwebsite.com/feed.xml is accessible"
echo ""
echo "4. Test metadata:"
echo "   - Visit a blog post page"
echo "   - View page source and verify meta tags are present"
echo "   - Check for JSON-LD structured data"
echo ""

# Step 6: Monitor Performance
echo "📍 STEP 6: Monitor Your SEO Performance"
echo "========================================="
echo "Weekly:"
echo "  ✓ Check Google Search Console for crawl errors"
echo "  ✓ Monitor search impressions and click-through rates"
echo "  ✓ Check Core Web Vitals"
echo ""
echo "Monthly:"
echo "  ✓ Review Google Analytics traffic"
echo "  ✓ Check keyword rankings"
echo "  ✓ Analyze top-performing content"
echo "  ✓ Update underperforming content"
echo ""
echo "Quarterly:"
echo "  ✓ Run full SEO audit"
echo "  ✓ Check backlink profile"
echo "  ✓ Review and update old content"
echo "  ✓ Analyze competitor strategies"
echo ""

# Step 7: Optimization Tips
echo "📍 STEP 7: Continuous SEO Optimization"
echo "========================================"
echo "Content:"
echo "  ✓ Write high-quality, in-depth blog posts"
echo "  ✓ Use target keywords naturally"
echo "  ✓ Create descriptive meta titles and descriptions"
echo "  ✓ Add internal links to related articles"
echo "  ✓ Update old posts with new information"
echo ""
echo "Technical:"
echo "  ✓ Ensure HTTPS is enabled"
echo "  ✓ Optimize page load speed"
echo "  ✓ Fix broken links regularly"
echo "  ✓ Implement proper redirects (301)"
echo "  ✓ Use responsive design"
echo ""
echo "Images:"
echo "  ✓ Compress images"
echo "  ✓ Use WebP format where possible"
echo "  ✓ Add descriptive alt text"
echo "  ✓ Use responsive image sizes"
echo ""
echo "Social:"
echo "  ✓ Share blog posts on social media"
echo "  ✓ Encourage backlinks from quality sites"
echo "  ✓ Build relationships with other bloggers"
echo "  ✓ Engage with your audience"
echo ""

echo ""
echo "====================================="
echo "✅ Configuration Complete!"
echo "====================================="
echo ""
echo "Need help? Check: src/lib/SEO_DOCUMENTATION.js"
echo "For more details: See SEO_IMPROVEMENTS_SUMMARY.md"
